spring:
  application:
    name: camly
  profiles:
    active: @spring.profiles.active@
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          "[time_zone]": UTC

server:
  compression:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  info:
    git:
      mode: full
    env:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true

logging:
  level:
    root: INFO
    "[andrehsvictor.camly]": INFO
    "[org.springframework.security]": INFO
