CREATE TABLE IF NOT EXISTS posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    image_url VARCHAR(255) NOT NULL,
    like_count INT DEFAULT 0,
    comment_count INT DEFAULT 0,
    caption VARCHAR(255) NOT NULL,
    engagement_rate FLOAT DEFAULT 0,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);